export 'package:platosyplan/presentation/views/user/update_profile_view.dart';
export 'package:platosyplan/presentation/views/user/profile_view.dart';
export 'package:platosyplan/presentation/views/loading_view.dart';
export 'package:platosyplan/presentation/views/auth/register.dart';
export 'package:platosyplan/presentation/views/auth/login.dart';
export 'package:platosyplan/presentation/views/recets/all_recets.dart';
export 'package:platosyplan/presentation/views/cookings_steps_view.dart';
export 'package:platosyplan/presentation/views/recipe_view.dart';
export 'package:platosyplan/presentation/views/introduction_view.dart';